print("Testing Speed")
print("")
print("Testing Download Speed...")
print("Download Speed = 1409/MiB")
print("")
print("Testing Upload Speed")
print("Upload Speed = 1426/MiB")
print("")
print("")
print("Speedtest By Ookla")
print("Visit https://www.speedtest.net/")
